services:
  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secure-message-backend
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secure-message-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_BASE_URL=http://backend:8086  # URL for backend communication
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
